name: zap_dev
description: Developer tooling for `zap`, a reactive web framework.
version: 0.2.4
homepage: https://simonbinder.eu/zap/

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.2.0
  args: ^2.3.0
  build: ^2.1.1
  build_version: ^2.1.0
  collection: ^1.15.0
  csslib: ^1.0.0
  crypto: ^3.0.1
  dart_style: ^2.2.0
  path: ^1.8.0
  pool: ^1.5.0
  recase: ^4.0.0
  sass_api: ^8.0.0
  sass: ^1.62.1
  source_span: ^1.8.1
  stack_trace: ^1.10.0
  watcher: ^1.0.1
  zap: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.7
  charcode: ^1.3.1
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  zap:
    path: ../zap
